" Set colorscheme
colorscheme nord

" Basic settings
set background=dark
set nobackup
set clipboard=unnamedplus
set cmdheight=1
set completeopt=menuone,noselect
set conceallevel=0
set encoding=utf-8
set fileencoding=utf-8
set hlsearch
set ignorecase
set mouse=a
set pumheight=10
set noshowmode
set showtabline=2
set smartcase
set smartindent
set splitbelow
set splitright
set noswapfile
set termguicolors
set timeoutlen=1000
set noundofile
set updatetime=300
set nowb
set expandtab
set shiftwidth=2
set tabstop=2
set cursorline
set number
set relativenumber
set numberwidth=4
set signcolumn=yes
set nowrap
set linebreak
set scrolloff=5
set sidescrolloff=8

" Shortmess options
set shortmess+=c

" Whichwrap settings
set whichwrap+=<,>,[,],h,l

" Iskeyword settings
set iskeyword+=-

" Format options
set formatoptions-=cro

" Additional settings that might be useful
set incsearch
set laststatus=2
set wildmenu
set wildmode=longest:full,full
set hidden
set autoread

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Set leader key to space
let mapleader = " "
let maplocalleader = " "

" Disable default keymap
nnoremap q <Nop>

" Better window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Resize with arrows
nnoremap <C-Up> :resize -2<CR>
nnoremap <C-Down> :resize +2<CR>
nnoremap <C-Left> :vertical resize -2<CR>
nnoremap <C-Right> :vertical resize +2<CR>

" Navigate buffers
nnoremap <S-l> :bnext<CR>
nnoremap <S-h> :bprevious<CR>

" Move text up and down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==

" Prevent copy on press x
nnoremap x "_x

" Increase & decrease number
nnoremap + <C-a>
nnoremap _ <C-x>

" Disable highlight
nnoremap <leader>nh :nohl<CR>

" Manipulating splits
nnoremap <leader>sv <C-w>v
nnoremap <leader>sh <C-w>s
nnoremap <leader>se <C-w>=
nnoremap <leader>sx :close<CR>

" Manipulating tabs
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>tx :tabclose<CR>
nnoremap <leader>th :tabp<CR>
nnoremap <leader>tl :tabn<CR>

" Press jk fast to enter normal mode
inoremap jk <ESC>

" Stay in indent mode
vnoremap < <gv
vnoremap > >gv

" Move text up and down in visual mode
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
vnoremap p "_dP

" Move text up and down in visual block mode
xnoremap J :move '>+1<CR>gv=gv
xnoremap K :move '<-2<CR>gv=gv
xnoremap <A-j> :move '>+1<CR>gv=gv
xnoremap <A-k> :move '<-2<CR>gv=gv

" Better terminal navigation
tnoremap <C-h> <C-\><C-n><C-w>h
tnoremap <C-j> <C-\><C-n><C-w>j
tnoremap <C-k> <C-\><C-n><C-w>k
tnoremap <C-l> <C-\><C-n><C-w>l
